export const ROUTES = {
  SPLASH: '/',
  ONBOARDING: '/onboarding',
  LOGIN: '/login',
  OTP: '/otp',
  PROFILE: '/profile-setup',
  PAN: '/pan',
  ADDRESS: '/address',
  BANK: '/bank',
  CONSENT: '/consent',
  ELIGIBILITY: '/eligibility',
  CREDIT_APPROVED: '/credit-approved',
  DASHBOARD: '/app/home',
  CREDIT: '/app/credit',
  PAYMENTS: '/app/payments',
  PROFILE_HOME: '/app/profile',
  GET_MONEY: '/app/get-money',
  LOAN_REVIEW: '/app/loan-review',
  LOAN_PROCESSING: '/app/loan-processing',
  LOAN_SUCCESS: '/app/loan-success',
  REPAYMENT_SCHEDULE: '/app/repayment-schedule',
  PAY_NOW: '/app/pay-now',
  TRANSACTIONS: '/app/transactions',
  CREDIT_DETAILS: '/app/credit-details',
  PROFILE_PERSONAL: '/app/profile/personal',
  PROFILE_BANK: '/app/profile/bank',
  PROFILE_DOCUMENTS: '/app/profile/documents',
  PROFILE_NOTIFICATIONS: '/app/profile/notifications',
  PROFILE_SECURITY: '/app/profile/security',
  PROFILE_HELP: '/app/profile/help',
  PROFILE_TERMS: '/app/profile/terms',
  PROFILE_PRIVACY: '/app/profile/privacy',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_HOME: '/admin',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_OPERATIONS: '/admin/operations',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_LOANS: '/admin/loans',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
